/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_HANGMAN: () => VIEW_TYPE_HANGMAN,
  default: () => FrenchVocabGamePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// VocabularyManager.ts
var import_obsidian = require("obsidian");
var VocabularyManager = class {
  constructor(app, vocabFilePath) {
    this.items = [];
    this.app = app;
    this.vocabFilePath = vocabFilePath;
  }
  async loadVocabulary() {
    console.log(`Loading vocabulary from: ${this.vocabFilePath}`);
    let file = this.app.vault.getAbstractFileByPath(this.vocabFilePath);
    if (!(file instanceof import_obsidian.TFile)) {
      console.warn(`Vocabulary file not found at exact path ${this.vocabFilePath}. Searching by name...`);
      const allFiles = this.app.vault.getMarkdownFiles();
      file = allFiles.find((f) => f.name === this.vocabFilePath || f.path.endsWith("/" + this.vocabFilePath));
    }
    if (!(file instanceof import_obsidian.TFile)) {
      console.error(`Vocabulary file not found at ${this.vocabFilePath}`);
      new import_obsidian.Notice(`Vocabulary file not found: ${this.vocabFilePath}`);
      return [];
    }
    console.log(`Reading vocabulary file: ${file.path}`);
    const content = await this.app.vault.read(file);
    this.items = this.parseVocabulary(content);
    console.log(`Parsed ${this.items.length} items from ${file.path}`);
    return this.items;
  }
  createVocabularyId(french, russian) {
    const normalize = (text) => text.trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, " ");
    return `${normalize(french)}||${russian.trim()}`;
  }
  createVocabularyItem(french, russian, category) {
    return {
      id: this.createVocabularyId(french, russian),
      french,
      russian,
      category
    };
  }
  hasCyrillic(text) {
    return /[\u0400-\u04FF]/.test(text);
  }
  inferFrenchRussian(first, second) {
    const firstHasCyrillic = this.hasCyrillic(first);
    const secondHasCyrillic = this.hasCyrillic(second);
    if (firstHasCyrillic && !secondHasCyrillic) {
      return { french: second, russian: first };
    }
    if (secondHasCyrillic && !firstHasCyrillic) {
      return { french: first, russian: second };
    }
    return { french: first, russian: second };
  }
  parseVocabulary(content) {
    const items = [];
    const lines = content.split("\n");
    let currentCategory = "Uncategorized";
    let tableHeaders = [];
    let isInsideTable = false;
    for (const line of lines) {
      const trimmedLine = line.trim();
      if (trimmedLine.startsWith("# ")) {
        currentCategory = trimmedLine.substring(2).trim();
        continue;
      }
      if (trimmedLine.startsWith("## ")) {
        currentCategory = trimmedLine.substring(3).trim();
        continue;
      }
      if (!trimmedLine) {
        isInsideTable = false;
        tableHeaders = [];
        continue;
      }
      if (trimmedLine.startsWith("|")) {
        const cells = trimmedLine.split("|").map((c) => c.trim()).slice(1, -1);
        if (!isInsideTable) {
          if (trimmedLine.includes("---")) {
            continue;
          }
          tableHeaders = cells;
          isInsideTable = true;
          continue;
        }
        if (trimmedLine.includes("---")) {
          continue;
        }
        const frenchIdx = tableHeaders.findIndex(
          (h) => h.toLowerCase().includes("french") || h.toLowerCase().includes("verb") || h.toLowerCase().includes("word")
        );
        const russianIdx = tableHeaders.findIndex(
          (h) => h.toLowerCase().includes("russian") || h.toLowerCase().includes("translate") || h.toLowerCase().includes("translation")
        );
        if (frenchIdx !== -1 && russianIdx !== -1 && cells[frenchIdx] && cells[russianIdx]) {
          items.push(this.createVocabularyItem(cells[frenchIdx], cells[russianIdx], currentCategory));
        } else if (cells.length >= 2) {
          const pair = this.inferFrenchRussian(cells[0], cells[cells.length - 1]);
          items.push(this.createVocabularyItem(pair.french, pair.russian, currentCategory));
        }
        continue;
      }
      let processedLine = trimmedLine;
      if (processedLine.startsWith("- ") || processedLine.startsWith("* ") || processedLine.startsWith("\u2022 ")) {
        processedLine = processedLine.substring(2).trim();
      }
      let parts = [];
      const separators = [" - ", " : ", " = ", " \u2013 ", " \u2014 ", " :: ", " -", "- ", " :", ": "];
      for (const sep of separators) {
        if (processedLine.includes(sep)) {
          parts = processedLine.split(sep);
          break;
        }
      }
      if (parts.length < 2) {
        const fallback = processedLine.match(/(.+?)\s*[-–—=]{1,2}\s*(.+)/);
        if (fallback) {
          parts = [fallback[1], fallback[2]];
        }
      }
      if (parts.length >= 2) {
        const firstPart = parts[0].trim();
        const secondPart = parts.slice(1).join(" - ").replace(/\[\]\(\)/g, "").trim();
        const pair = this.inferFrenchRussian(firstPart, secondPart);
        if (pair.french && pair.russian && !pair.french.endsWith(":")) {
          items.push(this.createVocabularyItem(pair.french, pair.russian, currentCategory));
        }
      }
    }
    return items;
  }
};

// SRSEngine.ts
var SRSEngine = class {
  // SM-2 Algorithm implementation
  // Quality of response:
  // 0: Complete blackout
  // 1: Incorrect response; the correct one remembered
  // 2: Incorrect response; where the correct one seemed easy to recall
  // 3: Correct response recalled with serious difficulty
  // 4: Correct response after a hesitation
  // 5: Perfect response
  static processReview(item, id, quality) {
    let repetition = item ? item.repetition : 0;
    let interval = item ? item.interval : 0;
    let easeFactor = item ? item.easeFactor : 2.5;
    if (quality >= 3) {
      if (repetition === 0) {
        interval = 1;
      } else if (repetition === 1) {
        interval = 6;
      } else {
        interval = Math.round(interval * easeFactor);
      }
      repetition += 1;
    } else {
      repetition = 0;
      interval = 1;
    }
    easeFactor = easeFactor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
    if (easeFactor < 1.3) {
      easeFactor = 1.3;
    }
    const nextReviewDate = Date.now() + interval * 24 * 60 * 60 * 1e3;
    return {
      id,
      repetition,
      interval,
      easeFactor,
      nextReviewDate
    };
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  vocabFilePath: "Vocabulaire.md",
  srsData: {}
};
var VIEW_TYPE_HANGMAN = "hangman-view";
var HangmanView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentWord = null;
    this.guessedLetters = /* @__PURE__ */ new Set();
    this.mistakes = 0;
    this.maxMistakes = 6;
    this.direction = "ru->fr";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_HANGMAN;
  }
  getDisplayText() {
    return "French Hangman";
  }
  async onOpen() {
    this.container = this.contentEl;
    this.container.empty();
    this.container.addClass("french-hangman-container");
    this.container.createEl("h2", { text: "Hangman: Apprenons le fran\xE7ais!" });
    this.hangmanDrawing = this.container.createEl("div", { cls: "hangman-drawing" });
    this.promptDisplay = this.container.createEl("div", { cls: "hangman-prompt" });
    this.wordDisplay = this.container.createEl("div", { cls: "hangman-word" });
    this.statusDisplay = this.container.createEl("div", { cls: "hangman-status" });
    this.keyboardContainer = this.container.createEl("div", { cls: "hangman-keyboard" });
    const controls = this.container.createEl("div", { cls: "hangman-controls" });
    this.directionDisplay = controls.createEl("div", { cls: "hangman-direction" });
    const nextBtn = controls.createEl("button", { text: "Next Word" });
    nextBtn.onclick = () => this.startNewGame();
    const switchBtn = controls.createEl("button", { text: "Switch Direction" });
    switchBtn.onclick = () => this.startNewGame(this.direction === "ru->fr" ? "fr->ru" : "ru->fr");
    await this.plugin.loadVocabulary();
    this.startNewGame();
  }
  startNewGame(direction) {
    if (direction) {
      this.direction = direction;
    } else {
      this.direction = Math.random() < 0.5 ? "ru->fr" : "fr->ru";
    }
    const word = this.plugin.getNextWordToReview();
    if (!word) {
      this.currentWord = null;
      this.guessedLetters.clear();
      this.mistakes = 0;
      this.promptDisplay.setText("No words available. Check your vocabulary file.");
      this.wordDisplay.setText("");
      this.statusDisplay.setText("");
      this.hangmanDrawing.setText("");
      this.keyboardContainer.empty();
      return;
    }
    this.currentWord = word;
    this.guessedLetters.clear();
    this.mistakes = 0;
    this.updateDisplay();
    this.renderKeyboard();
  }
  cleanWordForGame(word) {
    if (this.direction === "ru->fr") {
      return word.replace(/\([mf]\)/g, "").trim().toLowerCase();
    }
    return word.trim().toLowerCase();
  }
  handleGuess(letter) {
    if (!this.currentWord || this.guessedLetters.has(letter) || this.mistakes >= this.maxMistakes || this.isGameWon()) {
      return;
    }
    this.guessedLetters.add(letter);
    const targetWord = this.cleanWordForGame(this.direction === "ru->fr" ? this.currentWord.french : this.currentWord.russian);
    const unaccentedTarget = targetWord.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
    if (!targetWord.includes(letter) && !unaccentedTarget.includes(letter)) {
      this.mistakes++;
    }
    this.updateDisplay();
    this.renderKeyboard();
    this.checkGameEnd();
  }
  isGameWon() {
    if (!this.currentWord)
      return false;
    const targetWord = this.cleanWordForGame(this.direction === "ru->fr" ? this.currentWord.french : this.currentWord.russian);
    const letterPattern = this.direction === "ru->fr" ? /[a-zœæéèêëàâäùûüôöîïçœæ]/i : /[а-яё]/i;
    for (const char of targetWord) {
      if (char.match(letterPattern)) {
        const unaccentedChar = char.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
        if (!this.guessedLetters.has(char) && !this.guessedLetters.has(unaccentedChar)) {
          return false;
        }
      }
    }
    return true;
  }
  checkGameEnd() {
    var _a, _b;
    if (this.isGameWon()) {
      this.statusDisplay.setText("\u{1F389} F\xE9licitations! You got it right!");
      this.plugin.recordReview(this.currentWord.id, this.mistakes === 0 ? 5 : this.mistakes <= 2 ? 4 : 3);
    } else if (this.mistakes >= this.maxMistakes) {
      const answer = this.direction === "ru->fr" ? (_a = this.currentWord) == null ? void 0 : _a.french : (_b = this.currentWord) == null ? void 0 : _b.russian;
      this.statusDisplay.setText(`\u274C Dommage... The word was: ${answer}`);
      this.plugin.recordReview(this.currentWord.id, 1);
    }
  }
  updateDisplay() {
    if (!this.currentWord)
      return;
    const promptText = this.direction === "ru->fr" ? this.currentWord.russian : this.currentWord.french;
    const targetWord = this.cleanWordForGame(this.direction === "ru->fr" ? this.currentWord.french : this.currentWord.russian);
    const letterPattern = this.direction === "ru->fr" ? /[a-zœæéèêëàâäùûüôöîïçœæ]/i : /[а-яё]/i;
    this.directionDisplay.setText(this.direction === "ru->fr" ? "Direction: Russian \u2192 French" : "Direction: French \u2192 Russian");
    this.promptDisplay.setText(promptText);
    this.hangmanDrawing.setText(`Mistakes: ${this.mistakes} / ${this.maxMistakes}`);
    let displayText = "";
    for (const char of targetWord) {
      if (char.match(letterPattern)) {
        const unaccentedChar = char.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
        if (this.guessedLetters.has(char) || this.guessedLetters.has(unaccentedChar)) {
          displayText += char + " ";
        } else {
          displayText += "_ ";
        }
      } else {
        displayText += char + " . ";
      }
    }
    this.wordDisplay.setText(displayText.trim());
    if (this.mistakes < this.maxMistakes && !this.isGameWon()) {
      this.statusDisplay.setText("");
    }
  }
  renderKeyboard() {
    this.keyboardContainer.empty();
    const frenchKeys = "abcdefghijklmnopqrstuvwxyz\xE9\xE8\xEA\xEB\xE0\xE2\xE4\xF9\xFB\xFC\xF4\xF6\xEE\xEF\xE7\u0153\xE6-".split("");
    const russianKeys = "\u0430\u0431\u0432\u0433\u0434\u0435\u0451\u0436\u0437\u0438\u0439\u043A\u043B\u043C\u043D\u043E\u043F\u0440\u0441\u0442\u0443\u0444\u0445\u0446\u0447\u0448\u0449\u044A\u044B\u044C\u044D\u044E\u044F-".split("");
    const alphabet = this.direction === "ru->fr" ? frenchKeys : russianKeys;
    for (const letter of alphabet) {
      const btn = this.keyboardContainer.createEl("button", { text: letter });
      if (this.guessedLetters.has(letter)) {
        btn.disabled = true;
        btn.addClass("guessed");
      }
      btn.onclick = () => this.handleGuess(letter);
    }
  }
  async onClose() {
  }
};
var FrenchVocabGamePlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.vocabManager = new VocabularyManager(this.app, this.settings.vocabFilePath);
    this.registerView(
      VIEW_TYPE_HANGMAN,
      (leaf) => new HangmanView(leaf, this)
    );
    this.addRibbonIcon("dice", "Play French Hangman", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-french-hangman",
      name: "Open French Hangman Game",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new FrenchVocabGameSettingTab(this.app, this));
  }
  async loadVocabulary() {
    try {
      await this.vocabManager.loadVocabulary();
    } catch (e) {
      new import_obsidian2.Notice("Failed to load vocabulary. Check the file path in settings.");
    }
  }
  getNextWordToReview() {
    if (this.vocabManager.items.length === 0)
      return null;
    const now = Date.now();
    let dueWords = [];
    let newWords = [];
    for (const item of this.vocabManager.items) {
      const srs = this.settings.srsData[item.id];
      if (!srs) {
        newWords.push(item);
      } else if (srs.nextReviewDate <= now) {
        dueWords.push(item);
      }
    }
    if (dueWords.length > 0) {
      return dueWords[Math.floor(Math.random() * dueWords.length)];
    } else if (newWords.length > 0) {
      return newWords[Math.floor(Math.random() * newWords.length)];
    }
    return this.vocabManager.items[Math.floor(Math.random() * this.vocabManager.items.length)];
  }
  async recordReview(wordId, quality) {
    const currentSrs = this.settings.srsData[wordId];
    const updatedSrs = SRSEngine.processReview(currentSrs, wordId, quality);
    this.settings.srsData[wordId] = updatedSrs;
    await this.saveSettings();
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_HANGMAN);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getLeaf(true);
      await leaf.setViewState({ type: VIEW_TYPE_HANGMAN, active: true });
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var FrenchVocabGameSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Vocabulary File Path").setDesc("Path to the markdown file containing vocabulary (e.g., Vocabulaire.md)").addText((text) => text.setPlaceholder("Vocabulaire.md").setValue(this.plugin.settings.vocabFilePath).onChange(async (value) => {
      this.plugin.settings.vocabFilePath = value;
      this.plugin.vocabManager.vocabFilePath = value;
      await this.plugin.saveSettings();
      await this.plugin.loadVocabulary();
    }));
  }
};
